apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aimmo-game
  namespace: default
spec:
  endpoints:
    - targetport: 80
  selector:
    matchLabels:
      app: aimmo-game    
